webtalk_init -webtalk_dir C:/Users/mkw-desktop/OneDrive - Cal Poly/Documents/Vivado/CPE233/CPE233.sim/sim_1/behav/xsim/xsim.dir/PCReg_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jan 11 14:55:54 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "41d6b684-4426-40dd-8708-ec71adca8224" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cd862b0fbdb447f8b511e6ba55650249" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3700X 8-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "60 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7372_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1088342533 -regid "" -xml C:/Users/mkw-desktop/OneDrive - Cal Poly/Documents/Vivado/CPE233/CPE233.sim/sim_1/behav/xsim/xsim.dir/PCReg_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/mkw-desktop/OneDrive - Cal Poly/Documents/Vivado/CPE233/CPE233.sim/sim_1/behav/xsim/xsim.dir/PCReg_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/mkw-desktop/OneDrive - Cal Poly/Documents/Vivado/CPE233/CPE233.sim/sim_1/behav/xsim/xsim.dir/PCReg_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
